restackio/examples-python

readme.md
What this PR does?
Updates the main readme file of the repository
=> Update main repo readme

examples/gemini_generate_content/pyproject.toml, examples/gemini_generate_content/schedule_workflow.py, examples/gemini_generate_content/src/client.py, examples/gemini_generate_content/src/functions/function.py, examples/gemini_generate_content/src/services.py, examples/gemini_generate_content/src/workflows/gemini_generate_content.py
What this PR does?
Adds an example of using `restack_integrations_gemini`
=> Add Gemini example

examples/openai_greet/pyproject.toml, examples/openai_greet/src/functions/function.py
Fixes the example to use the right OpenAI integration
=> Fix OpenAI example

examples/gemini_generate_content/README.md
Updates the README for Gemini example with the step by step tutorial & overall basic description of the example
=> Update README for Gemini example

examples/streamlit_fastapi_togetherai_llama/.gitignore, examples/streamlit_fastapi_togetherai_llama/README.md
Edit gitignore and fixed readme
=> change readme for streamlit

.gitignore, examples/custom_llm_gemini/poetry.lock, examples/fastapi_gemini_feedback/pyproject.toml, examples/fastapi_gemini_feedback/src/workflows/gemini_generate_content.py, examples/fastapi_togetherai_llama/poetry.lock, examples/fastapi_togetherai_llama/pyproject.toml, examples/fastapi_togetherai_llama/src/workflows/workflow.py, examples/flask_gemini/poetry.lock, examples/flask_gemini/pyproject.toml, examples/flask_gemini/src/workflows/gemini_generate_content.py, examples/flask_togetherai_llamaindex/poetry.lock, examples/flask_togetherai_llamaindex/pyproject.toml, examples/flask_togetherai_llamaindex/src/workflows/workflow.py, examples/gemini_generate/poetry.lock, examples/gemini_generate/pyproject.toml, examples/gemini_generate/src/workflows/gemini_generate_content.py, examples/get-started/pyproject.toml, examples/get-started/src/workflows/workflow.py, examples/human_loop/pyproject.toml, examples/human_loop/src/workflows/workflow.py, examples/openai_greet/pyproject.toml, examples/openai_greet/src/workflows/openai_greet.py, examples/streamlit/pyproject.toml, examples/weaviate_search/pyproject.toml, examples/weaviate_search/src/workflows/workflow.py
- Bump all examples to restack_ai 0.0.25
- Update everywhere to use import_functions
=> 0.0.25 import functions

examples/fastapi_togetherai_llama/pyproject.toml, examples/fastapi_togetherai_llama/src/app.py, examples/fastapi_togetherai_llama/src/functions/function.py, examples/fastapi_togetherai_llama/src/workflows/workflow.py, examples/flask_gemini/README.md, examples/flask_gemini/pyproject.toml, examples/flask_gemini/src/app.py, examples/flask_gemini/src/functions/function.py, examples/flask_gemini/src/workflows/gemini_generate_content.py, examples/flask_togetherai_llamaindex/pyproject.toml, examples/flask_togetherai_llamaindex/src/workflows/workflow.py, examples/gemini_generate/pyproject.toml, examples/gemini_generate/schedule_workflow.py, examples/gemini_generate/src/functions/function.py, examples/gemini_generate/src/workflows/gemini_generate_content.py, examples/get-started/pyproject.toml, examples/get-started/schedule_workflow.py, examples/get-started/src/functions/function.py, examples/get-started/src/services.py, examples/get-started/src/workflows/workflow.py, examples/openai_greet/pyproject.toml, examples/openai_greet/schedule_workflow.py, examples/openai_greet/src/functions/function.py, examples/openai_greet/src/workflows/openai_greet.py, examples/streamlit_fastapi_togetherai_llama/pyproject.toml, examples/streamlit_fastapi_togetherai_llama/src/app.py, examples/streamlit_fastapi_togetherai_llama/src/functions/function.py, examples/streamlit_fastapi_togetherai_llama/src/workflows/workflow.py
Simplify & cleanup
Removed InputParams (translated from `stupid json` from Notion)
Removed `restack_openai` integration, works without it
Updated to use dataclasses, added a log statement in the workflow
Updated to use dataclasses, added a log statement in the workflow
Updated to a newer restack_ai version with updated logs
Changed to use dataclasses, updated logging, updated readme, removed restack-gemini integration
=> Update all examples

examples/weaviate_search/pyproject.toml, examples/weaviate_search/schedule_workflow.py, examples/weaviate_search/src/workflows/workflow.py
Updates `restack_ai` version to 0.0.26
Adds descriptive logging
=> Update weaviate_search example

examples/human_loop/pyproject.toml, examples/human_loop/schedule_workflow.py, examples/human_loop/src/workflows/workflow.py
Updated the human_loop example with updated `restack_ai` version and descriptive logging
=> Update human_loop example

examples/llama_quickstart/src/functions/crawl/website.py, examples/llama_quickstart/src/functions/hn/search.py
Update error handling for `llama-quickstart` example to be compatible with the latest logging feature
=> Update error handling on llama-quickstart example

examples/fastapi_gemini_feedback/.env.example, examples/fastapi_gemini_feedback/README.md, examples/fastapi_gemini_feedback/poetry.lock, examples/fastapi_gemini_feedback/pyproject.toml, examples/fastapi_gemini_feedback/src/client.py, examples/fastapi_gemini_feedback/src/functions/function.py, examples/fastapi_gemini_feedback/src/workflows/gemini_generate_content.py
Environment and Configuration: Added GEMINI_API_KEY to .env.example and updated endpoint URLs to 0.0.0.0. Improved instructions for API key configuration.
Dependency Updates: Upgraded fastapi, google-api-core, google-api-python-client, and restack-ai to newer versions for compatibility and improvements.
Code and Bug Fixes: Reorganized imports for PEP8 compliance, improved code structure, and fixed a bug with the end_workflow variable assignment.
=> [Fix] Fastapi Gemini Feedback

examples/defense_quickstart/restack_up.py
Updates quickstart with deployable Restack Engine
=> Defence quickstart: update up

examples/encryption/README.md, examples/encryption/pyproject.toml, examples/encryption/schedule_workflow.py, examples/encryption/src/client.py, examples/encryption/src/codec.py, examples/encryption/src/codec_server.py, examples/encryption/src/functions/function.py, examples/encryption/src/services.py, examples/encryption/src/workflows/workflow.py
Add encryption example to showcase end-end encryption security
https://github.com/restackio/restack/pull/158
=> Encrypted workflow example

examples/defense_quickstart_audio_transcription_translation/README.md, examples/defense_quickstart_news_scraper_summarizer/README.md
Fixing the streamlit run command in the readme
=> Fix streamlit run command in readme

examples/defense_quickstart_audio_transcription_translation/README.md, examples/defense_quickstart_news_scraper_summarizer/README.md
Fixes missing spacing in the poetry run streamlit command
=> Fix missing spacing

examples/defense_quickstart_denoise/README.md
updates the readme of denoise example with audio datasets link
=> Update readme with dataset link

defense_quickstart_audio_transcription_translation/restack_up.py
Fixes restack_up by adding missing env variables
=> Fix restack_up for transcribe example

email_sender/README.md, stripe-ai/.env.example, stripe-ai/README.md, stripe-ai/pyproject.toml, stripe-ai/schedule_workflow.py, stripe-ai/src/client.py, stripe-ai/src/functions/create_payment_link.py, stripe-ai/src/services.py, stripe-ai/src/workflows/payment_link.py
Example of using Restack AI alongside Langchain to interact with stripe ai sdk. The agent will create a product on stripe alongside a payment link.
=> Stripe ai sdk example

bostondynamics_spot/pyproject.toml, child_workflows/pyproject.toml, defense_quickstart_audio_transcription_translation/pyproject.toml, defense_quickstart_denoise/pyproject.toml, defense_quickstart_news_scraper_summarizer/pyproject.toml, encryption/pyproject.toml, fastapi_gemini_feedback/pyproject.toml, fastapi_togetherai_llama/pyproject.toml, flask_gemini/pyproject.toml, flask_togetherai_llamaindex/pyproject.toml, gemini_generate/pyproject.toml, get_started/pyproject.toml, human_loop/pyproject.toml, llama_quickstart/pyproject.toml, openai_greet/pyproject.toml, streamlit/pyproject.toml, streamlit_fastapi_togetherai_llama/pyproject.toml, weaviate_search/pyproject.toml
- Update all examples to match restack-ai 0.0.45 bringing Restack Cloud compatibility
=> Bump all examples for Restack Cloud Engine

copilot.sh, copilot.txt
A quick hack during the AI in production Hackathon feat Softbank
- Attempt at testing a generated file with all examples to help users generate functions or workflows with AI Copilot
=> Test a txt files with all examples for Ai copilot

audio_transcript/pyproject.toml, defense_quickstart_audio_transcription_translation/pyproject.toml, defense_quickstart_news_scraper_summarizer/pyproject.toml, email_sender/pyproject.toml, openai_greet/pyproject.toml, pdf_pydantic/pyproject.toml, production_demo/pyproject.toml, stripe_ai/pyproject.toml
- Some examples have OpenAI SDK error
error Client.__init__() got an unexpected keyword argument 'proxies'
=> bump openai

audio_transcript/Dockerfile, defense_quickstart_audio_transcription_translation/Dockerfile, defense_quickstart_denoise/Dockerfile, defense_quickstart_news_scraper_summarizer/Dockerfile, fastapi_togetherai_llama/Dockerfile, llama_quickstart/Dockerfile, openai_greet/Dockerfile, production_demo/Dockerfile, quickstart/Dockerfile
- remove --no-dev as its not a valid command for poetry install
=> Dockerfile fix remove non existent command

quickstart/.env.Example, quickstart/src/client.py
- Add API address to client to have endpoints on deployed cloud
=> Quickstart add api address

quickstart/src/services.py
=> Quickstart run services

agent_apis/pyproject.toml, agent_chat/pyproject.toml, agent_rag/pyproject.toml, agent_todo/pyproject.toml, agent_tool/pyproject.toml
Removing the code left from the development process locally
=> Use public restack_ai package

agent_apis/pyproject.toml, agent_apis/src/workflows/multistep.py, agent_chat/pyproject.toml, agent_chat/src/agents/agent.py, agent_rag/pyproject.toml, agent_rag/src/agents/chat_rag.py, agent_todo/pyproject.toml, agent_todo/src/agents/agent_todo.py, agent_todo/src/workflows/todo_execute.py, agent_tool/pyproject.toml, agent_tool/src/agents/chat_tool_functions.py
Correct the input handling of the step() method in agent examples
=> Correct input agents

agent_apis/pyproject.toml, agent_chat/pyproject.toml, agent_rag/pyproject.toml, agent_todo/pyproject.toml, agent_tool/pyproject.toml
Update to the correct version of restack_ai while maintaining compatibility with Python 3.10
=> Correct restack_ai version and stay with python 3.10

agent_apis/pyproject.toml, agent_chat/pyproject.toml, agent_rag/pyproject.toml, agent_todo/pyproject.toml, agent_tool/pyproject.toml
Update restack_ai version in agent examples to align with the latest changes
=> Bump restack_ai version for agent examples

agent_rag/src/agents/chat_rag.py, agent_rag/src/services.py
Fix function name typos by replacing lookupSales with the correct lookup_sales function
=> Agent_rag example fix typo

agent_apis/.env.Example, agent_apis/src/functions/llm.py, agent_chat/.env.Example, agent_chat/src/functions/llm_chat.py, agent_humanloop/.env.Example, agent_rag/src/functions/llm_chat.py, agent_stream/.env.Example, agent_stream/src/functions/llm_chat.py, agent_telephony/twilio_livekit/agent_twilio/.env.Example, agent_telephony/vapi/agent_vapi/.env.Example, agent_telephony/vapi/agent_vapi/src/functions/llm_chat.py, agent_todo/.env.Example, agent_todo/src/functions/llm_chat.py, agent_tool/src/functions/llm_chat.py, agent_video/src/functions/llm_chat.py, agent_voice/livekit/agent/.env.example, agent_voice/livekit/agent/src/functions/llm_chat.py, agent_voice/livekit/livekit_pipeline/.env.example, encryption/.env.example, pdf_ocr/.env.Example, pdf_ocr/src/functions/openai_chat.py, production_demo/.env.Example
This PR:
- Adds OPENAI_API_KEY as default
- Removes base url of ai.restack
- Removes RESTACK_ENGINE envs from env.example files
=> Make onboarding better
